### ISSUE TITLE
Catch vision whne there's no battery plugged in

### ISSUE THREAD

**Issue by SamJinLi** [Team-6220/6220_2025#31]
When we turn the robot on, we have to plug in the battery for vision, otherwise, the code will crash. If we make a catch statement to catch that, it will help us with developing.

**Comment by leetokuda** [comment]
Hi Sam,

This could be the same problem described in [Issue #30](https://github.com/Team-6220/6220_2025/issues/30).  You can try the suggested fix in there.

Thanks,
Lee

**Comment by SamJinLi** [comment]
How I fixed it: the error was talking about how the cameras weren't receiving anything, there weren't any network table showing up. So the fix was that I just don't call the function that checks for the network table until we need to use it.

**Comment by leetokuda** [comment]
Hi Sam,

Just a minor note: The problem was that the periodic() method in PhotonVisionSubsystem.java was crashing when the cameras were un-powered.  Your fix was to move that periodic() code to a new method: updatePhoton().  Since updatePhoton() only gets called when a button is pushed, you didn't see the crash when the cameras were un-powered.  But you would still see the crash if you had pushed the button while the cameras were unpowered.  So the change only hid the problem behind a button push, rather than fix it.  It probably doesn't matter at this point but it's always good to try to understand the root cause of the problem and fix it, rather than work around it.

Thanks,
Lee

**Comment by SamJinLi** [comment]
Hi Lee,

I'll test your code on the actual robot on Tuesday. Should I reopen the issue and make a new branch to fix it, or something else? Also, do you think it's ok to keep my updatePhoton(), or should I test with the older version before my changes?

Thank you!
Sam
